config/routes.rb
Loggas::Application.routes.draw do
  resources :produtos

  get "detales/index"

  get "detales/show"

  get "detales/new"

  get "detales/edit"

  resources :consultors

  resources :tecnicos

  resources :servicos

  resources :implates do
     resources :detales 
  end 
  resources :clientes

  resources :notafiscals

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
      validates_presence_of :nome
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  # GET /clientes
  # GET /clientes.json
  def index
    @search = Cliente.search(params[:q])
    @clientes = @search.result

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clientes }
    end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/new
  # GET /clientes/new.json
  def new
    @cliente = Cliente.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(params[:cliente])

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente criado com sucesso.' }
        format.json { render json: @cliente, status: :created, location: @cliente }
      else
        format.html { render action: "new" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.json
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        format.html { redirect_to @cliente, notice: 'Cliente atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente, :html => {:class => "form-horizontal"}) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation", class="alert alert-error">
      <h3><%= pluralize(@cliente.errors.count, "Erro(s)") %> impede(m) de salvar:</h3>
       <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <fieldset>
  <div class="control-group">
    <%= f.label :nome,:class =>'control-label' %>
    <div class="controls">
    
    <%= f.text_field :nome %>
    </div>
    </div>
  <div class="control-group">
    <%= f.label :endereco,:class =>'control-label' %>
    <div class="controls">
    
    <%= f.text_field :endereco %>
    </div>
    </div>
  <div class="control-group">
    <%= f.label :bairro,:class =>'control-label' %>
    <div class="controls">
    
    <%= f.text_field :bairro %>
    </div>
    </div>
  <div class="control-group">
    <%= f.label :cidade,:class =>'control-label' %>
    <div class="controls">
    
    <%= f.text_field :cidade %>
    </div>
    </div>
  <div class="control-group">
    <%= f.label :uf, :class =>'control-label' %>
    <div class="controls">
    
    <%= f.select :uf, ['CE', 'AC', 'AL', 'AP', 'AM', 'BA', 'DF', 'GO', 'ES', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SP', 'SC', 'SE', 'TO'] %>
    </div>
    </div>
  <div class="control-group">
    <%= f.label :telefone,:class =>'control-label' %>
    <div class="controls">
    
    <%= f.telephone_field :telefone %>
    </div>
    </div>
  <div class="control-group">
    <%= f.label :email,:class =>'control-label' %>
    <div class="controls">
    
    <%= f.email_field :email %>
    </div>
    </div>
  <div class="control-group">
    <%= f.label :contato,:class =>'control-label' %>
    <div class="controls">
    
    <%= f.text_field :contato %>
    </div>
    </div>
<br/>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-small btn-primary' %>
    <%= link_to 'Voltar', clientes_path, :class=>'btn btn-small' %>
  </div>
</fieldset>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editando Cliente</h1>

<%= render 'form' %>

app/views/clientes/index.html.erb
<div class="page-header">
  <h1>Clientes cadastrados</h1>
</div>
<!-- Button to trigger modal -->
<% if Cliente.find(:all).size == @clientes.size %>
<a href="#myModal" role="button" class="btn btn-small" data-toggle="modal">Filtrar</a>
<% else %>
<a href="#myModal" role="button" class="btn btn-small btn-danger" data-toggle="modal">Filtrado</a>
<% end %>
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Filtrar Registros</h3>
  </div>
  <div class="modal-body">
    <%= search_form_for @search do |f| %>
    <div class="field">
     <%= f.label :nome_cont, "Contendo o nome" %>
     <%= f.text_field :nome_cont %>
   </div>
   </div>
  <div class="modal-footer">
    <%= f.submit "Filtar", :class=>'btn btn-primary' %>
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button> 
  </div>
  <% end %>
</div>

<!-- Fim do Modal-->
<table class="table table-striped table-condensed">
  <tr>
    <th><%= sort_link @search, :nome ,"Nome" %></th>
    <th><%= sort_link @search, :endereco ,"Endereco" %></th>
    <th><%= sort_link @search, :bairro ,"Bairro" %></th>
    <th><%= sort_link @search, :cidade ,"Cidade" %></th>
    <th><%= sort_link @search, :uf ,"UF" %></th>
    <th><%= sort_link @search, :telefone ,"Telefone" %></th>
    <th><%= sort_link @search, :email ,"Email" %></th>
    <th><%= sort_link @search, :contato ,"Contato" %></th>
 </tr>

<% @clientes.each do |cliente| %>
  <tr>
    <td><%= cliente.nome %></td>
    <td><%= cliente.endereco%></td>
    <td><%= cliente.bairro%></td>
    <td><%= cliente.cidade %></td>
    <td><%= cliente.uf %></td>
    <td><%= cliente.telefone%></td>
    <td><%= cliente.email %></td>
    <td><%= cliente.contato %></td>
    <td><%= link_to 'Editar', edit_cliente_path(cliente),:class => "btn btn-mini" %> <%= link_to 'Apagar', cliente, confirm: 'Desejas Apagar?', method: :delete ,:class => 'btn btn-mini btn-danger'%></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Adicionar Cliente', new_cliente_path, :class => "btn btn-small btn-primary" %>

app/views/clientes/new.html.erb
<h1>Adicionar Cliente</h1>

<%= render 'form' %>

app/views/clientes/show.html.erb
<p id="notice" class="alert alert-success"><%= notice %></p>
<div class="page-header">
  <h1>Cliente</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Nome:</strong></dt>
  <dd><%= @cliente.nome.size > 0?"#{@cliente.nome}":" - " %></dd>
  <dt><strong>Endereco:</strong></dt>
  <dd><%= @cliente.endereco.size > 0?"#{@cliente.endereco}":" - " %></dd>
  <dt><strong>Bairro:</strong></dt>
  <dd><%= @cliente.bairro.size > 0?"#{@cliente.bairro}":" - " %></dd>
  <dt><strong>Cidade:</strong></dt>
  <dd><%= @cliente.cidade.size > 0?"#{@cliente.cidade}":" - " %></dd>
  <dt><strong>Uf:</strong></dt>
  <dd><%= @cliente.uf %></dd>
  <dt><strong>Telefone:</strong></dt>
  <dd><%= @cliente.telefone.size > 0?"#{@cliente.telefone}":" - " %></dd>
  <dt><strong>Email:</strong></dt>
  <dd><%= @cliente.email.size > 0?"#{@cliente.email}":" - " %></dd>
  <dt><strong>Contato:</strong></dt>
  <dd><%= @cliente.contato.size > 0?"#{@cliente.contato}":" - " %></dd>
</dl>

<div class="form-actions">
  <%= link_to 'Voltar', clientes_path, :class=>"btn" %>
  <%= link_to 'Editar', edit_cliente_path(@cliente),:class => "btn" %> 
  <%= link_to 'Apagar', @cliente, confirm: 'Desejas Apagar?',method: :delete ,:class => 'btn btn-danger'%>
</div>