config/routes.rb
Loggas::Application.routes.draw do
  resources :produtos

  get "detales/index"

  get "detales/show"

  get "detales/new"

  get "detales/edit"

  resources :consultors

  resources :tecnicos

  resources :servicos

  resources :implates do
     resources :detales 
  end 
  resources :clientes

  resources :notafiscals

end

app/models/notafiscal.rb
class Notafiscal < ActiveRecord::Base
   validates_presence_of :numero, :valor
   validates_uniqueness_of :numero
   belongs_to :cliente, :foreign_key => :cliente_id
end

app/controllers/notafiscals_controller.rb
class NotafiscalsController < ApplicationController
  # GET /notafiscals
  # GET /notafiscals.json
  def index
    @notafiscals = Notafiscal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notafiscals }
    end
  end

  # GET /notafiscals/1
  # GET /notafiscals/1.json
  def show
    @notafiscal = Notafiscal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notafiscal }
    end
  end

  # GET /notafiscals/new
  # GET /notafiscals/new.json
  def new
    @notafiscal = Notafiscal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notafiscal }
    end
  end

  # GET /notafiscals/1/edit
  def edit
    @notafiscal = Notafiscal.find(params[:id])
  end

  # POST /notafiscals
  # POST /notafiscals.json
  def create
    @notafiscal = Notafiscal.new(params[:notafiscal])

    respond_to do |format|
      if @notafiscal.save
        format.html { redirect_to @notafiscal, notice: 'Notafiscal criado com sucesso.' }
        format.json { render json: @notafiscal, status: :created, location: @notafiscal }
      else
        format.html { render action: "new" }
        format.json { render json: @notafiscal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notafiscals/1
  # PUT /notafiscals/1.json
  def update
    @notafiscal = Notafiscal.find(params[:id])

    respond_to do |format|
      if @notafiscal.update_attributes(params[:notafiscal])
        format.html { redirect_to @notafiscal, notice: 'Notafiscal atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notafiscal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notafiscals/1
  # DELETE /notafiscals/1.json
  def destroy
    @notafiscal = Notafiscal.find(params[:id])
    @notafiscal.destroy

    respond_to do |format|
      format.html { redirect_to notafiscals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/notafiscals_helper.rb
module NotafiscalsHelper
end

app/views/notafiscals/_form.html.erb
<%= form_for(@notafiscal, :html => {:class => "form-horizontal"}) do |f| %>
  <% if @notafiscal.errors.any? %>
    <div id="error_explanation" class="alert alert-error">
      <h3><%= pluralize(@notafiscal.errors.count, "error") %> prohibited this notafiscal from being saved:</h3>
       <ul>
      <% @notafiscal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <fieldset>
  <div class="control-group">
    <%= f.label :numero,:class =>'control-label' %>
    <div class="controls">
    
    <%= f.text_field :numero %>
    </div>
    </div>
  <div class="control-group">
    <%= f.label :data,:class =>'control-label' %>
    <div class="controls">
    
    <%= f.date_select :data, :order => [:day, :month, :year], :use_month_names => %w(Janeiro Fevereiro Marco Abril Maio Junho Julho Agosto Setembro Outubro Novembro Dezembro)%>
    </div>
    </div>
  <div class="control-group">
    <%= f.label :cliente, :class =>'control-label' %>
    <div class="controls">
    
    <%= f.collection_select :cliente_id, Cliente.find(:all), :id, :nome %>
    </div>
    </div>
  <div class="control-group">
    <%= f.label :valor,:class =>'control-label' %>
    <div class="controls">
    
    <%= f.text_field :valor %>
    </div>
    </div>
  <div class="control-group">
    <%= f.label :status,:class =>'control-label' %>
    <div class="controls">
    
    <%= f.text_field :status %>
    </div>
    </div>
  <div class="control-group">
    <%= f.label :ok,:class =>'control-label' %>
    <div class="controls">
    
    <%= f.check_box :ok %>
    </div>
    </div>
<br/>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-small btn-primary' %>
    <%= link_to 'Voltar', notafiscals_path, :class=>'btn btn-small' %>
  </div>
</fieldset>
<% end %>

app/views/notafiscals/edit.html.erb
<h1>Editando Nota Fiscal</h1>

<%= render 'form' %>

app/views/notafiscals/index.html.erb
<div class="page-header">
  <h1>Notas Fiscais Cadastradas</h1>
</div>

<table class="table table-striped table-condensed">
  <tr>
    <th>Numero</th>
    <th>Data</th>
    <th>Cliente</th>
    <th>Valor</th>
    <th>Status</th>
    <th>Ok</th>
    <th></th>
 </tr>

<% @notafiscals.each do |notafiscal| %>
  <tr>
    <td><%= notafiscal.numero %></td>
    <td><%= notafiscal.data.strftime("%d/%m/%Y") %></td>
    <td><%= notafiscal.cliente.nome %></td>
    <td><%= notafiscal.valor %></td>
    <td><%= notafiscal.status %></td>
    <% if notafiscal.ok.to_s == 'true' %> 
      <td> <span class="badge badge-success">S</span> </td>
    <%else%>
     <td> <span class="badge badge-important">N</span> </td> 
    <%end%>
    <td><%= link_to 'Editar', edit_notafiscal_path(notafiscal),:class => "btn btn-mini" %> <%= link_to 'Apagar', notafiscal, confirm: 'Desejas Apagar?', method: :delete ,:class => 'btn btn-mini btn-danger'%></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Adicionar Nota Fiscal', new_notafiscal_path, :class => "btn btn-small btn-primary" %>

app/views/notafiscals/new.html.erb
<h1>Adicionar Nota Fiscal</h1>

<%= render 'form' %>

app/views/notafiscals/show.html.erb
<p id="notice" class="alert alert-info"><%= notice %></p>
<div class="page-header">
  <h1>Nota Fiscal</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Numero:</strong></dt>
  <dd><%= @notafiscal.numero %> </dd>
  <dt><strong>Data:</strong></dt>
  <dd><%= @notafiscal.data.strftime("%d/%m/%Y") %></dd>
  <dt><strong>Cliente:</strong></dt>
  <dd><%= @notafiscal.cliente.nome %></dd>
  <dt><strong>Valor:</strong></dt>
  <dd><%= @notafiscal.valor %></dd>
  <dt><strong>Status:</strong></dt>
  <dd><%= @notafiscal.status.size > 0?"#{@notafiscal.status}":" - "%></dd>
  <dt><strong>Ok:</strong></dt>
   <% if @notafiscal.ok.to_s == 'true' %> 
   <dd> <span class="badge badge-success">S</span> </dd>
    <%else%>
     <dd> <span class="badge badge-important">N</span> </dd> 
    <%end%>
</dl>

<div class="form-actions">
  <%= link_to 'Voltar', notafiscals_path, :class=>"btn" %>
  <%= link_to 'Editar', edit_notafiscal_path(@notafiscal),:class => "btn" %> 
  <%= link_to 'Apagar', @notafiscal, confirm: 'Desejas Apagar?',method: :delete ,:class => 'btn btn-danger'%>
</div>