config/routes.rb
Loggas::Application.routes.draw do
  resources :produtos

  get "detales/index"

  get "detales/show"

  get "detales/new"

  get "detales/edit"

  resources :consultors

  resources :tecnicos

  resources :servicos

  resources :implates do
     resources :detales 
  end 
  resources :clientes

  resources :notafiscals

end

app/models/tecnico.rb
class Tecnico < ActiveRecord::Base
end

app/controllers/tecnicos_controller.rb
class TecnicosController < ApplicationController
  # GET /tecnicos
  # GET /tecnicos.json
  def index
    @tecnicos = Tecnico.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tecnicos }
    end
  end

  # GET /tecnicos/1
  # GET /tecnicos/1.json
  def show
    @tecnico = Tecnico.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tecnico }
    end
  end

  # GET /tecnicos/new
  # GET /tecnicos/new.json
  def new
    @tecnico = Tecnico.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tecnico }
    end
  end

  # GET /tecnicos/1/edit
  def edit
    @tecnico = Tecnico.find(params[:id])
  end

  # POST /tecnicos
  # POST /tecnicos.json
  def create
    @tecnico = Tecnico.new(params[:tecnico])

    respond_to do |format|
      if @tecnico.save
        format.html { redirect_to @tecnico, notice: 'Tecnico criado com sucesso.' }
        format.json { render json: @tecnico, status: :created, location: @tecnico }
      else
        format.html { render action: "new" }
        format.json { render json: @tecnico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tecnicos/1
  # PUT /tecnicos/1.json
  def update
    @tecnico = Tecnico.find(params[:id])

    respond_to do |format|
      if @tecnico.update_attributes(params[:tecnico])
        format.html { redirect_to @tecnico, notice: 'Tecnico atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tecnico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tecnicos/1
  # DELETE /tecnicos/1.json
  def destroy
    @tecnico = Tecnico.find(params[:id])
    @tecnico.destroy

    respond_to do |format|
      format.html { redirect_to tecnicos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tecnicos_helper.rb
module TecnicosHelper
end

app/views/tecnicos/_form.html.erb
<%= form_for(@tecnico, :html => {:class => "form-horizontal"}) do |f| %>
  <% if @tecnico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tecnico.errors.count, "error") %> prohibited this tecnico from being saved:</h2>
       <ul>
      <% @tecnico.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <fieldset>
  <div class="control-group">
    <%= f.label :nome,:class =>'control-label' %>
    <div class="controls">
    
    <%= f.text_field :nome %>
    </div>
    </div>
  <div class="control-group">
    <%= f.label :telefone,:class =>'control-label' %>
    <div class="controls">
    
    <%= f.text_field :telefone %>
    </div>
    </div>
  <div class="control-group">
    <%= f.label :email,:class =>'control-label' %>
    <div class="controls">
    
    <%= f.text_field :email %>
    </div>
    </div>
<br/>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-small btn-primary' %>
    <%= link_to 'Voltar', tecnicos_path, :class=>'btn btn-small' %>
  </div>
</fieldset>
<% end %>

app/views/tecnicos/edit.html.erb
<h1>Editando tecnico</h1>

<%= render 'form' %>

app/views/tecnicos/index.html.erb
<div class="page-header">
  <h1>tecnicos cadastrados</h1>
</div>

<table class="table table-striped table-condensed">
  <tr>
    <th>Nome</th>
    <th>Telefone</th>
    <th>Email</th>
    <th></th>
 </tr>

<% @tecnicos.each do |tecnico| %>
  <tr>
    <td><%= tecnico.nome %></td>
    <td><%= tecnico.telefone %></td>
    <td><%= tecnico.email %></td>
    <td><%= link_to 'Editar', edit_tecnico_path(tecnico),:class => "btn btn-mini" %> <%= link_to 'Apagar', tecnico, confirm: 'Desejas Apagar?', method: :delete ,:class => 'btn btn-mini btn-danger'%></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Adicionar Tecnico', new_tecnico_path, :class => "btn btn-small btn-primary" %>

app/views/tecnicos/new.html.erb
<h1>Adicionar tecnico</h1>

<%= render 'form' %>

app/views/tecnicos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
  <h1>tecnico</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Nome:</strong></dt>
  <dd><%= @tecnico.nome %></dd>
  <dt><strong>Telefone:</strong></dt>
  <dd><%= @tecnico.telefone %></dd>
  <dt><strong>Email:</strong></dt>
  <dd><%= @tecnico.email %></dd>
</dl>

<div class="form-actions">
  <%= link_to 'Voltar', tecnicos_path, :class=>"btn" %>
  <%= link_to 'Editar', edit_tecnico_path(@tecnico),:class => "btn" %> 
  <%= link_to 'Apagar', @tecnico, confirm: 'Desejas Apagar?',method: :delete ,:class => 'btn btn-danger'%>
</div>