config/routes.rb
Loggas::Application.routes.draw do
  resources :produtos

  get "detales/index"

  get "detales/show"

  get "detales/new"

  get "detales/edit"

  resources :consultors

  resources :tecnicos

  resources :servicos

  resources :implates do
     resources :detales 
  end 
  resources :clientes

  resources :notafiscals

end

app/models/produto.rb
class Produto < ActiveRecord::Base
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @produtos }
    end
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
    @produto = Produto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @produto }
    end
  end

  # GET /produtos/new
  # GET /produtos/new.json
  def new
    @produto = Produto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @produto }
    end
  end

  # GET /produtos/1/edit
  def edit
    @produto = Produto.find(params[:id])
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(params[:produto])

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto criado com sucesso.' }
        format.json { render json: @produto, status: :created, location: @produto }
      else
        format.html { render action: "new" }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /produtos/1
  # PUT /produtos/1.json
  def update
    @produto = Produto.find(params[:id])

    respond_to do |format|
      if @produto.update_attributes(params[:produto])
        format.html { redirect_to @produto, notice: 'Produto atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto = Produto.find(params[:id])
    @produto.destroy

    respond_to do |format|
      format.html { redirect_to produtos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_for(@produto, :html => {:class => "form-horizontal"}) do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h2>
       <ul>
      <% @produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <fieldset>
  <div class="control-group">
    <%= f.label :descricao,:class =>'control-label' %>
    <div class="controls">
    
    <%= f.text_field :descricao %>
    </div>
    </div>
  <div class="control-group">
    <%= f.label :quantidade,:class =>'control-label' %>
    <div class="controls">
    
    <%= f.number_field :quantidade %>
    </div>
    </div>
  <div class="control-group">
    <%= f.label :compra,:class =>'control-label' %>
    <div class="controls">
    
    <%= f.text_field :compra %>
    </div>
    </div>
  <div class="control-group">
    <%= f.label :venda,:class =>'control-label' %>
    <div class="controls">
    
    <%= f.text_field :venda %>
    </div>
    </div>
  <div class="control-group">
    <%= f.label :minimo,:class =>'control-label' %>
    <div class="controls">
    
    <%= f.number_field :minimo %>
    </div>
    </div>
  <div class="control-group">
    <%= f.label :fornecedor,:class =>'control-label' %>
    <div class="controls">
    
    <%= f.text_field :fornecedor %>
    </div>
    </div>
<br/>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-small btn-primary' %>
    <%= link_to 'Voltar', produtos_path, :class=>'btn btn-small' %>
  </div>
</fieldset>
<% end %>

app/views/produtos/edit.html.erb
<h1>Editando produto</h1>

<%= render 'form' %>

app/views/produtos/index.html.erb
<div class="page-header">
  <h1>produtos cadastrados</h1>
</div>

<table class="table table-striped table-condensed">
  <tr>
    <th>Descricao</th>
    <th>Quantidade</th>
    <th>Compra</th>
    <th>Venda</th>
    <th>Minimo</th>
    <th>Fornecedor</th>
    <th></th>
 </tr>

<% @produtos.each do |produto| %>
  <tr>
    <td><%= produto.descricao %></td>
    <td><%= produto.quantidade %></td>
    <td><%= produto.compra %></td>
    <td><%= produto.venda %></td>
    <td><%= produto.minimo %></td>
    <td><%= produto.fornecedor %></td>
    <td><%= link_to 'Editar', edit_produto_path(produto),:class => "btn btn-mini" %> <%= link_to 'Apagar', produto, confirm: 'Desejas Apagar?', method: :delete ,:class => 'btn btn-mini btn-danger'%></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Adicionar Produto', new_produto_path, :class => "btn btn-small btn-primary" %>

app/views/produtos/new.html.erb
<h1>Adicionar produto</h1>

<%= render 'form' %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
  <h1>produto</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Descricao:</strong></dt>
  <dd><%= @produto.descricao %></dd>
  <dt><strong>Quantidade:</strong></dt>
  <dd><%= @produto.quantidade %></dd>
  <dt><strong>Compra:</strong></dt>
  <dd><%= @produto.compra %></dd>
  <dt><strong>Venda:</strong></dt>
  <dd><%= @produto.venda %></dd>
  <dt><strong>Minimo:</strong></dt>
  <dd><%= @produto.minimo %></dd>
  <dt><strong>Fornecedor:</strong></dt>
  <dd><%= @produto.fornecedor %></dd>
</dl>

<div class="form-actions">
  <%= link_to 'Voltar', produtos_path, :class=>"btn" %>
  <%= link_to 'Editar', edit_produto_path(@produto),:class => "btn" %> 
  <%= link_to 'Apagar', @produto, confirm: 'Desejas Apagar?',method: :delete ,:class => 'btn btn-danger'%>
</div>